# Generated by Django 4.2 on 2023-04-22 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherextra',
            name='first_name',
            field=models.CharField(default='firstname', max_length=50),
        ),
        migrations.AddField(
            model_name='teacherextra',
            name='last_name',
            field=models.CharField(default='lastname', max_length=50),
        ),
    ]
