# Generated by Django 4.2 on 2023-04-22 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_teacherextra_first_name_teacherextra_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentextra',
            name='first_name',
            field=models.CharField(default='firstname', max_length=50),
        ),
        migrations.AddField(
            model_name='studentextra',
            name='last_name',
            field=models.CharField(default='lastname', max_length=50),
        ),
    ]
