# Generated by Django 4.2 on 2023-04-26 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_studentextra_first_name_studentextra_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='cl',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='date',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='roll',
        ),
        migrations.AddField(
            model_name='attendance',
            name='student',
            field=models.ForeignKey(default=9, on_delete=django.db.models.deletion.CASCADE, to='attendance.studentextra'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='present_status',
            field=models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent')], max_length=10),
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classs', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('attendance_records', models.ManyToManyField(default=9, through='attendance.Attendance', to='attendance.studentextra')),
            ],
        ),
        migrations.AddField(
            model_name='attendance',
            name='attendance_record',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='attendance.attendancerecord'),
        ),
    ]
