# Generated by Django 4.2 on 2023-04-26 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_remove_attendance_cl_remove_attendance_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='attendance_record',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='student',
        ),
        migrations.AddField(
            model_name='attendance',
            name='cl',
            field=models.CharField(default='one', max_length=10),
        ),
        migrations.AddField(
            model_name='attendance',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='roll',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.DeleteModel(
            name='AttendanceRecord',
        ),
    ]
