# Generated by Django 4.2 on 2023-04-26 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_alter_attendance_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='roll',
            field=models.CharField(max_length=10),
        ),
    ]
